### ISSUE TITLE
Small typos

### ISSUE THREAD

**Issue by cmaldonadolens** [TheLens/citysalaries#4]
Under department names, &s are showing up as &amp. Also "Tax research" appears as "Ta Research."

**Comment by AbeHandler** [comment]
Ampersands are fixed. Search on ampersand seemed to be a bug in the old application, fixed in the new one. 

Not going to fix "TA  RESEARCH" because that is how they spell the department in the underlying data and I don't feel comfortable changing this because I don't totally understand what it means.
